# Generated by Django 5.2 on 2025-04-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserevenue',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_record', to='customers.purchase'),
        ),
    ]
